import Head from "next/head";
import Fullpage, {
  FullPageSections,
  FullpageSection,
} from "@ap.cx/react-fullpage";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Services from "@/components/Services";
import Works from "@/components/Works";
import Review from "@/components/Clients";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      {/*/////////////////////////////////////
    /////////  Head Information  ////////////
    //////////////////////////////////////*/}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*/////////////////////////////////////
    /////////////  Main Body   //////////////
    //////////////////////////////////////*/}
      <Fullpage>
        <FullPageSections>
          <FullpageSection>
            <Hero />
          </FullpageSection>
          <FullpageSection>
            <About />
          </FullpageSection>
          <FullpageSection>
            <Services />
          </FullpageSection>
          <FullpageSection>
            <Works />
          </FullpageSection>
          <FullpageSection>
            <Review />
          </FullpageSection>
          <FullpageSection>
            <Contact />
          </FullpageSection>
          <FullpageSection>
            <Footer />
          </FullpageSection>
        </FullPageSections>
      </Fullpage>
    </>
  );
}
